recipes.addShaped(<Torcherino:tile.compressed_torcherino>, [[<Torcherino:tile.torcherino>, <Torcherino:tile.torcherino>, <Torcherino:tile.torcherino>], [<Torcherino:tile.torcherino>, <ProjectE:item.pe_time_watch>, <Torcherino:tile.torcherino>], [<Torcherino:tile.torcherino>, <Torcherino:tile.torcherino>, <Torcherino:tile.torcherino>]]);
recipes.addShaped(<Torcherino:tile.double_compressed_torcherino>, [[<Torcherino:tile.compressed_torcherino>, <Torcherino:tile.compressed_torcherino>, <Torcherino:tile.compressed_torcherino>], [<Torcherino:tile.compressed_torcherino>, <ProjectE:item.pe_time_watch>, <Torcherino:tile.compressed_torcherino>], [<Torcherino:tile.compressed_torcherino>, <Torcherino:tile.compressed_torcherino>, <Torcherino:tile.compressed_torcherino>]]);
recipes.addShaped(<Torcherino:tile.torcherino>, [[<ProjectE:item.pe_time_watch>, <PortalGun:MiniBlackHole>, <ProjectE:item.pe_time_watch>], [<EE3:matter:4>, <Avaritia:Resource:9>, <EE3:matter:4>], [<ore:stickObsidian>, <minecraft:nether_star>, <ore:stickObsidian>]]);

recipes.addShaped(<furnus:furnus>, [[<ore:ingotTin>, <minecraft:brick_block>, <ore:ingotTin>], [<minecraft:brick_block>, <minecraft:furnace>, <minecraft:brick_block>], [<ore:sand>, <minecraft:brick_block>, <ore:sand>]]);
recipes.addShaped(<furnus:pulvus>, [[<ore:ingotTin>, <ore:sandstone>, <ore:ingotTin>], [<ore:sandstone>, <exnihilo:hammer_iron>, <ore:sandstone>], [<excompressum:compressed_dust:5>, <minecraft:furnace>, <excompressum:compressed_dust:5>]]);

recipes.addShaped(<CBMReborn:CondensedCobble:1>, [[<CBMReborn:CondensedCobble>, <CBMReborn:CondensedCobble>, <CBMReborn:CondensedCobble>], [<CBMReborn:CondensedCobble>, <CBMReborn:CondensedCobble>, <CBMReborn:CondensedCobble>], [<CBMReborn:CondensedCobble>, <CBMReborn:CondensedCobble>, <CBMReborn:CondensedCobble>]]);
recipes.addShaped(<CBMReborn:CondensedCobble:2>, [[<CBMReborn:CondensedCobble:1>, <CBMReborn:CondensedCobble:1>, <CBMReborn:CondensedCobble:1>], [<CBMReborn:CondensedCobble:1>, <CBMReborn:CondensedCobble:1>, <CBMReborn:CondensedCobble:1>], [<CBMReborn:CondensedCobble:1>, <CBMReborn:CondensedCobble:1>, <CBMReborn:CondensedCobble:1>]]);
recipes.addShaped(<CBMReborn:CondensedCobble:3>, [[<CBMReborn:CondensedCobble:2>, <CBMReborn:CondensedCobble:2>, <CBMReborn:CondensedCobble:2>], [<CBMReborn:CondensedCobble:2>, <CBMReborn:CondensedCobble:2>, <CBMReborn:CondensedCobble:2>], [<CBMReborn:CondensedCobble:2>, <CBMReborn:CondensedCobble:2>, <CBMReborn:CondensedCobble:2>]]);
recipes.addShaped(<CBMReborn:CondensedCobble>, [[<ore:compressedCobblestone8x>, <ore:compressedCobblestone8x>, <ore:compressedCobblestone8x>], [<ore:compressedCobblestone8x>, <ore:compressedCobblestone8x>, <ore:compressedCobblestone8x>], [<ore:compressedCobblestone8x>, <ore:compressedCobblestone8x>, <ore:compressedCobblestone8x>]]);
recipes.addShaped(<CBMReborn:CondensedBone>, [[<minecraft:bone>, <minecraft:bone>, <minecraft:bone>], [<minecraft:bone>, <minecraft:bone>, <minecraft:bone>], [<minecraft:bone>, <minecraft:bone>, <minecraft:bone>]]);

recipes.addShaped(<lootbags:loot_recycler>, [[<ore:ingotIron>, <minecraft:piston>, <ore:ingotIron>], [<ThermalExpansion:material>, <ore:chestWood>, <ThermalExpansion:material>], [<ore:ingotIron>, <lootbags:lootbag:4>, <ore:ingotIron>]]);

recipes.addShaped(<imc:item_adamantium_helmet>, [[<imc:item_adamantium_ingot>, <imc:item_adamantium_ingot>, <imc:item_adamantium_ingot>], [<imc:item_adamantium_ingot>, <minecraft:diamond_helmet>, <imc:item_adamantium_ingot>]]);
recipes.addShaped(<imc:item_adamantium_boots>, [[<ore:ingotAdamantium>, <minecraft:diamond_boots>, <ore:ingotAdamantium>], [<ore:ingotAdamantium>, null, <ore:ingotAdamantium>]]);
recipes.addShaped(<imc:item_adamantium_leggings>, [[<ore:ingotAdamantium>, <imc:item_adamantium_ingot>, <ore:ingotAdamantium>], [<ore:ingotAdamantium>, <minecraft:diamond_leggings>, <ore:ingotAdamantium>], [<ore:ingotAdamantium>, null, <ore:ingotAdamantium>]]);
recipes.addShaped(<imc:item_adamantium_chestplate>, [[<ore:ingotAdamantium>, <minecraft:diamond_chestplate>, <ore:ingotAdamantium>], [<ore:ingotAdamantium>, <imc:item_adamantium_ingot>, <ore:ingotAdamantium>], [<ore:ingotAdamantium>, <ore:ingotAdamantium>, <ore:ingotAdamantium>]]);
recipes.addShaped(<imc:item_wooden_bucket>, [[<TConstruct:heavyPlate>, <IguanaTweaksTConstruct:clayBucketFired>, <TConstruct:heavyPlate>], [null, <TConstruct:heavyPlate>, null]]);

recipes.addShaped(<SolarFlux:solar4>, [[<ThermalExpansion:Glass:1>, <MekanismGenerators:Generator:5>, <ThermalExpansion:Glass:1>], [<MekanismGenerators:Generator:5>, <ore:thermalexpansion:machineFrame>, <MekanismGenerators:Generator:5>], [<ThermalExpansion:Frame:5>, <ore:awesomeCore>, <ThermalExpansion:Frame:5>]]);
recipes.addShaped(<SolarFlux:solar3>, [[<ore:waferAdvanced>, <MekanismGenerators:SolarPanel>, <ore:waferAdvanced>], [<GalacticraftCore:tile.solar:4>, <ore:awesomeCore>, <GalacticraftCore:tile.solar:4>], [<ore:waferAdvanced>, <MekanismGenerators:SolarPanel>, <ore:waferAdvanced>]]);
recipes.addShaped(<SolarFlux:solar2>, [[<SolarFlux:solarCell1>, <SolarFlux:solarCell1>, <SolarFlux:solarCell1>], [<SolarFlux:solarCell1>, <ore:blockRedstone>, <SolarFlux:solarCell1>], [<ThermalExpansion:material:3>, <SolarFlux:solar1>, <ThermalExpansion:material:3>]]);
recipes.addShaped(<SolarFlux:solar8>, [[<SolarFlux:solarCell4>, <SolarFlux:solarCell4>, <SolarFlux:solarCell4>], [<SolarFlux:solarCell4>, <EnderIO:blockSolarPanel:1>, <SolarFlux:solarCell4>], [<ThermalExpansion:material:3>, <ThermalExpansion:Frame:9>, <ThermalExpansion:material:3>]]);
recipes.addShaped(<SolarFlux:solar5>, [[<ore:blockGlassHardened>, <ore:blockGlassHardened>, <ThermalExpansion:Glass:1>], [<SolarFlux:solarCell3>, <EnderIO:blockSolarPanel>, <SolarFlux:solarCell3>], [<ore:itemVibrantCrystal>, <ore:awesomeCore>, <ore:itemVibrantCrystal>]]);
recipes.addShaped(<SolarFlux:solar1>, [[<SolarFlux:mirror>, <SolarFlux:mirror>, <SolarFlux:mirror>], [<SolarFlux:mirror>, <DraconicEvolution:sunFocus>, <SolarFlux:mirror>], [<ore:blockRedstone>, <ore:awesomeCore>, <ore:blockRedstone>]]);

recipes.addShaped(<StorageDrawers:upgradeVoid>, [[<ore:woodStick>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsvoid>, <ore:woodStick>], [<mo:tritanium_ingot>, <StorageDrawers:upgrade:6>, <mo:tritanium_ingot>], [<ore:woodStick>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsvoid>, <ore:woodStick>]]);
recipes.addShaped(<StorageDrawers:upgrade:6>, [[<ore:woodStick>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsemerald>, <ore:woodStick>], [<minecraft:emerald>, <StorageDrawers:upgrade:5>, <minecraft:emerald>], [<ore:woodStick>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsemerald>, <ore:woodStick>]]);
recipes.addShaped(<StorageDrawers:upgrade:5>, [[<ore:woodStick>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsdiamond>, <ore:woodStick>], [<minecraft:diamond>, <StorageDrawers:upgrade:4>, <minecraft:diamond>], [<ore:woodStick>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsdiamond>, <ore:woodStick>]]);
recipes.addShaped(<StorageDrawers:upgrade:4>, [[<ore:woodStick>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsobsidian>, <ore:woodStick>], [<TConstruct:materials:18>, <StorageDrawers:upgrade:3>, <TConstruct:materials:18>], [<ore:woodStick>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsobsidian>, <ore:woodStick>]]);
recipes.addShaped(<StorageDrawers:upgrade:3>, [[<ore:woodStick>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsgold>, <ore:woodStick>], [<ore:ingotGold>, <StorageDrawers:upgrade:2>, <ore:ingotGold>], [<ore:woodStick>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsgold>, <ore:woodStick>]]);
recipes.addShaped(<StorageDrawers:upgrade:2>, [[<ore:woodStick>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsiron>, <ore:woodStick>], [<minecraft:iron_ingot>, <StorageDrawers:upgradeTemplate>, <minecraft:iron_ingot>], [<ore:woodStick>, <BuildCraft|Transport:item.buildcraftPipe.pipeitemsiron>, <ore:woodStick>]]);
recipes.addShaped(<StorageDrawers:fullCustom4>, [[<minecraft:chest>, <minecraft:planks>, <minecraft:chest>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>], [<minecraft:chest>, <minecraft:planks>, <minecraft:chest>]]);
recipes.addShaped(<StorageDrawers:fullCustom2>, [[<minecraft:planks>, <minecraft:chest>, <minecraft:planks>], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>], [<minecraft:planks>, <minecraft:chest>, <minecraft:planks>]]);
recipes.addShaped(<StorageDrawers:fullCustom1>, [[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>], [null, <ore:chestWood>, null], [<ore:plankWood>, <ore:plankWood>, <ore:plankWood>]]);
recipes.addShaped(<StorageDrawers:controllerSlave>, [[<minecraft:stone>, <minecraft:stone>, <minecraft:stone>], [<minecraft:comparator>, <StorageDrawers:fullCustom1>, <minecraft:repeater>], [<minecraft:stone>, <minecraft:gold_block>, <minecraft:stone>]]);
recipes.addShaped(<StorageDrawers:controller>, [[<ore:stone>, <ore:stone>, <ore:stone>], [<minecraft:comparator>, <StorageDrawers:fullCustom1>, <minecraft:repeater>], [<ore:stone>, <ore:blockEmerald>, <ore:stone>]]);
recipes.addShaped(<StorageDrawers:compDrawers>, [[<ore:stone>, <ore:stone>, <ore:stone>], [<minecraft:piston>, <StorageDrawers:fullCustom1>, <minecraft:piston>], [<ore:stone>, <ore:blockIron>, <ore:stone>]]);
recipes.addShaped(<StorageDrawers:upgradeLock>, [[<ModuleG3:WhiteWarriorCompressed>, <minecraft:gold_block>], [<ModuleG3:WhiteWarriorCompressed>, <minecraft:gold_block>], [null, <StorageDrawers:upgradeVoid>]]);
recipes.addShaped(<StorageDrawers:shroudKey>, [[<minecraft:ender_eye>, <minecraft:ender_eye>, <minecraft:ender_eye>], [<minecraft:ender_eye>, <StorageDrawers:upgradeLock>, <minecraft:ender_eye>], [<minecraft:ender_eye>, <minecraft:ender_eye>, <minecraft:ender_eye>]]);
recipes.addShaped(<StorageDrawers:framingTable>, [[null, <TConstruct:CraftingSlab:2>, null], [<minecraft:wooden_slab:2>, <minecraft:crafting_table>, <minecraft:wooden_slab:2>], [<battlegear2:flagpole:2>, null, <battlegear2:flagpole:2>]]);
recipes.addShaped(<StorageDrawers:upgradeTemplate> * 2, [[<Natura:natura.stick:7>, <TConstruct:GlassBlock>, <Natura:natura.stick:7>], [<ExtraUtilities:decorativeBlock2>, <ore:drawerBasic>, <ExtraUtilities:decorativeBlock2>], [<Natura:natura.stick:7>, <TConstruct:GlassBlock>, <Natura:natura.stick:7>]]);
recipes.addShaped(<StorageDrawers:upgradeTemplate>, [[<Natura:natura.stick:7>, <ExtraUtilities:decorativeBlock2>, <Natura:natura.stick:7>], [<ExtraUtilities:decorativeBlock2>, <StorageDrawers:fullCustom1>, <ExtraUtilities:decorativeBlock2>], [<Natura:natura.stick:7>, <ExtraUtilities:decorativeBlock2>, <Natura:natura.stick:7>]]);
recipes.addShaped(<StorageDrawers:upgradeTemplate>, [[<Natura:natura.stick:7>, <ExtraUtilities:decorativeBlock2>, <Natura:natura.stick:7>], [<ExtraUtilities:decorativeBlock2>, <StorageDrawers:fullCustom4>, <ExtraUtilities:decorativeBlock2>], [<Natura:natura.stick:7>, <ExtraUtilities:decorativeBlock2>, <Natura:natura.stick:7>]]);
recipes.addShaped(<StorageDrawers:upgradeTemplate>, [[<Natura:natura.stick:7>, <ExtraUtilities:decorativeBlock2>, <Natura:natura.stick:7>], [<ExtraUtilities:decorativeBlock2>, <StorageDrawers:fullCustom2>, <ExtraUtilities:decorativeBlock2>], [<Natura:natura.stick:7>, <ExtraUtilities:decorativeBlock2>, <Natura:natura.stick:7>]]);

recipes.addShaped(<B0bGrowsOre:growingBlock>, [[<minecraft:reeds>, <MineFactoryReloaded:farmland>, <BiomesOPlenty:overgrownNetherrack>], [<minecraft:sand>, <minecraft:nether_star>, <minecraft:dirt>], [<TConstruct:CraftedSoil:5>, <Natura:soil.tainted>, <Natura:boneBag>]]);

recipes.addShaped(<RestrictedPortals:endKey>, [[<minecraft:end_portal_frame>, <EnderIO:itemFrankenSkull:2>, <minecraft:end_portal_frame>], [<Natura:planks:11>, <RestrictedPortals:netherKey>, <Natura:planks:11>], [<minecraft:end_portal_frame>, <EnderIO:itemFrankenSkull:4>, <minecraft:end_portal_frame>]]);
recipes.addShaped(<RestrictedPortals:netherKey>, [[<ore:netherMaterial>, <ore:itemBlazePowder>, <ore:netherMaterial>], [<TConstruct:heavyPlate:7>, <RandomThings:spectreKey>, <TConstruct:heavyPlate:7>], [<ore:netherMaterial>, <CBMReborn:CondensedGlowstone:3>, <ore:netherMaterial>]]);

recipes.addShaped(<IronChest:BlockIronChest:6>, [[<ore:blockObsidian>, <CBMReborn:CondensedObsidian>, <ore:blockObsidian>], [<ore:blockObsidian>, <IronChest:BlockIronChest:2>, <ore:blockObsidian>], [<ore:blockObsidian>, <ore:blockObsidian>, <ore:blockObsidian>]]);
recipes.addShaped(<IronChest:diamondObsidianUpgrade>, [[<ore:blockObsidian>, <CBMReborn:CondensedObsidian>, <ore:blockObsidian>], [<ore:blockObsidian>, <IronChest:goldDiamondUpgrade>, <ore:blockObsidian>], [<ore:blockObsidian>, <ore:blockObsidian>, <ore:blockObsidian>]]);
recipes.addShaped(<IronChest:BlockIronChest:2>, [[<ore:gemDiamond>, <ore:blockDiamond>, <ore:gemDiamond>], [<ore:gemDiamond>, <IronChest:BlockIronChest:1>, <ore:gemDiamond>], [<ore:gemDiamond>, <ore:gemDiamond>, <ore:gemDiamond>]]);
recipes.addShaped(<IronChest:goldDiamondUpgrade>, [[<ore:gemDiamond>, <ore:blockDiamond>, <ore:gemDiamond>], [<ore:gemDiamond>, <IronChest:silverGoldUpgrade>, <ore:gemDiamond>], [<ore:gemDiamond>, <ore:gemDiamond>, <ore:gemDiamond>]]);
recipes.addShaped(<IronChest:BlockIronChest:1>, [[<ore:ingotGold>, <ore:MainInfusionMaterial>, <ore:ingotGold>], [<ore:ingotGold>, <IronChest:BlockIronChest:4>, <ore:ingotGold>], [<ore:ingotGold>, <ore:ingotGold>, <ore:ingotGold>]]);
recipes.addShaped(<IronChest:silverGoldUpgrade>, [[<ore:ingotGold>, <ore:MainInfusionMaterial>, <ore:ingotGold>], [<ore:ingotGold>, <ore:ingotSilver>, <ore:ingotGold>], [<ore:ingotGold>, <ore:ingotGold>, <ore:ingotGold>]]);
recipes.addShaped(<IronChest:BlockIronChest:4>, [[<ThermalFoundation:material:66>, <ThermalFoundation:Storage:2>, <ThermalFoundation:material:66>], [<ThermalFoundation:material:66>, <IronChest:BlockIronChest>, <ThermalFoundation:material:66>], [<ThermalFoundation:material:66>, <ThermalFoundation:material:66>, <ThermalFoundation:material:66>]]);
recipes.addShaped(<IronChest:BlockIronChest>, [[<minecraft:iron_ingot>, <minecraft:iron_block>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <IronChest:BlockIronChest:3>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]]);
recipes.addShaped(<IronChest:copperIronUpgrade>, [[<minecraft:iron_ingot>, <minecraft:iron_block>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <ThermalFoundation:material:64>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]]);
recipes.addShaped(<IronChest:woodCopperUpgrade>, [[<ore:ingotCopper>, <ore:blockCopper>, <ore:ingotCopper>], [<ore:ingotCopper>, <minecraft:planks>, <ore:ingotCopper>], [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>]]);
recipes.addShaped(<IronChest:BlockIronChest:3>, [[<ore:ingotCopper>, <ore:blockCopper>, <ore:ingotCopper>], [<ore:ingotCopper>, <minecraft:chest>, <ore:ingotCopper>], [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>]]);

recipes.addShaped(<compacter:Compacter>, [[<minecraft:piston>, <excompressum:autoCompressor>, <minecraft:piston>], [<sr:IronPlate>, <Avaritia:Double_Craft>, <sr:IronPlate>], [<minecraft:piston>, <ThermalExpansion:material:1>, <minecraft:piston>]]);

recipes.addShapeless(<PracticalLogistics:Sapphire>, [<BiomesOPlenty:gems:6>]);

recipes.addShaped(<ComputerCraft:CC-Computer>, [[<GalacticraftCore:item.basicItem:11>, <GalacticraftCore:item.basicItem:11>, <GalacticraftCore:item.basicItem:11>], [<GalacticraftCore:item.basicItem:11>, <BuildCraft|Silicon:redstoneChipset:3>, <GalacticraftCore:item.basicItem:11>], [<GalacticraftCore:item.basicItem:11>, <ComputerCraft:CC-Peripheral:2>, <GalacticraftCore:item.basicItem:11>]]);
recipes.addShaped(<ComputerCraft:CC-Peripheral:2>, [[<GalacticraftCore:item.basicItem:11>, <GalacticraftCore:item.basicItem:11>, <GalacticraftCore:item.basicItem:11>], [<GalacticraftCore:item.basicItem:11>, <appliedenergistics2:item.ItemMultiPart:36>, <GalacticraftCore:item.basicItem:11>], [<GalacticraftCore:item.basicItem:11>, <appliedenergistics2:item.ItemMultiPart:180>, <GalacticraftCore:item.basicItem:11>]]);
recipes.addShaped(<ComputerCraft:CC-Peripheral:4>, [[<ModuleG3:WhiteWarriorCompressed>, <ModuleG3:WhiteWarriorCompressed>, <ModuleG3:WhiteWarriorCompressed>], [<ModuleG3:WhiteWarriorCompressed>, <appliedenergistics2:item.ItemMultiPart:76>, <ModuleG3:WhiteWarriorCompressed>], [<ModuleG3:WhiteWarriorCompressed>, <ComputerCraft:CC-Peripheral:2>, <ModuleG3:WhiteWarriorCompressed>]]);

recipes.addShaped(<ironbackpacks:jeweledFeather>, [[null, <CBMReborn:CondensedGold:3>, null], [<CBMReborn:CondensedGold:3>, <CBMReborn:CondensedFeather:3>, <CBMReborn:CondensedGold:3>], [null, <CBMReborn:CondensedGold:3>, null]]);
recipes.addShapeless(<ironbackpacks:treatedLeather>, [<minecraft:leather>, <minecraft:potion>, <ore:nuggetLead>, <TConstruct:toolShard:3>]);

recipes.addShaped(<ChickenChunks:chickenChunkLoader>, [[null, <EnderIO:itemMaterial:8>, null], [<ChickenChunks:chickenChunkLoader:1>, <minecraft:enchanting_table>, <ChickenChunks:chickenChunkLoader:1>], [<galaxymod:galaxymod_compressedgold>, <galaxymod:galaxymod_compressedgold>, <galaxymod:galaxymod_compressedgold>]]);
recipes.addShaped(<ChickenChunks:chickenChunkLoader>, [[null, <ChickenChunks:chickenChunkLoader:1>, null], [<ChickenChunks:chickenChunkLoader:1>, <minecraft:enchanting_table>, <ChickenChunks:chickenChunkLoader:1>], [<galaxymod:galaxymod_compressedgold>, <galaxymod:galaxymod_compressedgold>, <galaxymod:galaxymod_compressedgold>]]);
recipes.addShaped(<ChickenChunks:chickenChunkLoader:1>, [[null, <minecraft:ender_eye>, null], [<RandomThings:ingredient:6>, <minecraft:gold_ingot>, <RandomThings:ingredient:6>], [<minecraft:gold_ingot>, <minecraft:gold_block>, <minecraft:gold_ingot>]]);

recipes.addShaped(<PortalGun:MiniBlackHole>, [[<ore:itemPulsatingCrystal>, <RandomThings:ingredient:6>, <ore:itemPulsatingCrystal>], [<CBMReborn:CondensedEnderperl:1>, <ore:itemNetherStar>, <CBMReborn:CondensedEnderperl:1>], [<ore:itemPulsatingCrystal>, <RandomThings:ingredient:6>, <ore:itemPulsatingCrystal>]]);
recipes.addShaped(<PortalGun:LongFallBoot>, [[<TConstruct:heavyPlate:1000>, <EnderIO:itemAlloy:6>, <TConstruct:heavyPlate:1000>], [<TConstruct:heavyPlate:1000>, <Mekanism:CompressedDiamond>, <TConstruct:heavyPlate:1000>], [<TConstruct:heavyPlate:1000>, <Mekanism:CompressedDiamond>, <TConstruct:heavyPlate:1000>]]);

recipes.addShaped(<EnderStorage:enderChest>, [[<minecraft:blaze_rod>, <ThermalExpansion:Rockwool>, <minecraft:blaze_rod>], [<TurkeyUtil:Double_Compressed_Obsidian_Block>, <IronChest:BlockIronChest>, <TurkeyUtil:Double_Compressed_Obsidian_Block>], [<minecraft:blaze_rod>, <BiomesOPlenty:enderporter>, <minecraft:blaze_rod>]]);

print("loaded smallmods!");